# baseURL =
languageCode = 'en-us'
title = 'Rick Wysocki'
theme = "exampleTheme"


[params]

  # Site info
  author = 'Rick Wysocki'
  author_bio = "Teacher and Zen Buddhist living in Muncie, IN."

  # SEO
  description = 'Website and blog of Rick Wysocki.'
  site_image = 'images/bio-photo.png' # Add site-wide featured image here.
  # canonical_url = 'https://url.com'

  # Links / Socials
  email = 'rlwysockijr@gmail.com'
  github = 'rickwysocki'
  mastodon = 'https://mas.to/@rickwysocki'
  # twitter = '' fix user name
  # instagram = ''
  # facebook = ''

  # To-Do
  # Analytics


[menu]
  [[menu.main]]
    name = "Home"
    pre = "fa fa-home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Résumé"
    pre = "fa fa-tag"
    url = "/resume/"
    weight = 2
  [[menu.main]]
    name = "Posts"
    pre = "fa fa-keyboard"
    url = "/posts/"
    weight = 3
  [[menu.main]]
      name = "Teaching"
      pre = "fa fa-book"
      url = "/teaching/"
      weight = 4


[taxonomies]
  tag = "tags"
  course = 'courses'
  category = 'categories'
