baseURL = "https://www.rickwysocki.com/"
languageCode = 'en-us'
title = 'Rick Wysocki'
theme = ["hugo-embed-pdf-shortcode", "littleGhost"]
enableInlineShortcodes = true

[params]

  # Site info
  author = 'Rick Wysocki'
  author_bio = "Assistant Teaching Professor at Ball State University."
  long_bio = "I am a professor at Ball State University. I'm passionate about effective communication, research, and information design. My free time is spent learning new technologies, watching movies, and exploring new music."

  # SEO
  description = 'Website and blog of Rick Wysocki.'
  site_image = 'images/ghost.png' # Add site-wide featured image here.
  author_image = '/images/bio-photo.png' # Used for main author bio card.
  nav_logo = 'images/ghost.png' # Icon included in nav-bar.
  post_image = 'images/ghost-post-image.png'
  post_image_alt = 'Little Ghost logo.'


  # Links / Socials
  email = 'rlwysockijr@gmail.com'
  github = 'rickwysocki'
  mastodon = 'https://mas.to/@rickwysocki'
  # twitter = '' fix user name
  # instagram = ''
  # facebook = ''

  # To-Do
  # Analytics

pluralizeListTitles = false

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
      name = "Portfolio"
      url = "/portfolio/"
      weight = 3


[taxonomies]
  tag = "tags"
  course = 'courses'
  category = 'categories'
  project = 'projects'
  movie = 'movies'
  show = 'shows'
  skills = 'skills'

[permalinks]
  posts = '/posts/:year/:month/:title/'
  categories = '/:title/'
