#+hugo_base_dir: ../
* DONE AWS and the Enshittification of Educational Workflows
CLOSED: [2025-10-20 Mon 14:25]
:PROPERTIES:
:EXPORT_FILE_NAME: aws-and-the-enshittification-of-educational-workflows
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :summary "Canvas is down."
:END:
I am currently sitting in my office on campus. It is 1:57PM EST. I had planned a number of things to do today, most of which involved my teaching work: grading, lesson planning for tomorrow, following up with some students, etc. None of that is happening because, as an educational society, we have given up everything to LMS's. And AWS has them down.

As a lot of folks are experiencing right now, Amazon Web Services, the infrastructure on a good chunk of the modern web runs, is not working correctly. [[https://www.nytimes.com/2025/10/20/business/aws-down-internet-outage.html][The reasons for the outage are unclear]], and many websites are back online. Canvas, however--the learning management system that universities around the world have partnered with and require teachers to use for essentially all course-related activities--remains down.

It will be back up soon. My gripe is more with the fact that this is a perfect example of why [[/posts/2024-10-28-content-management-pedagogy/][content management pedagogy]] is such an odious phenomenon. The centralized role of learning management systems like Canvas leads to the following issues, for me, today:

1. I can't access assignments to grade, because students submit them to Canvas.
2. I can't access or update course materials. They are all required to be on Canvas.
3. I can't communicate with my students as a whole. Believe it or not, I am fairly certain that there is no actual way for me to message my classes except through Canvas. I could search for their names, one by one, in Outlook (another technology I don't like for another discusison), but guess where my course rosters are?

Cory Doctorow's concept of [[https://www.wired.com/story/tiktok-platforms-cory-doctorow/][enshittification]] refers to a predictable pattern where technologies create value for users, create value for businesses, create value for themselves, and then die because their platform no longer provides any use, enjoyment, or value for anyone. Monopolization he explains, is both a feature and an outcome involved in this process. Once a tool becomes the only game in town, it's free to dominate the contexts in which it's used.

Canvas isn't a monopoly, but at a broader scale LMS's have monopolized education. I often ask my students: do you all even like learning management systems like LMS's? Not one student has ever indicated anything positive about them.

Yet, we still have to use them, because all schools (not just universities) in the US have ceded educational ground to them, feeding them money and [[https://dl.acm.org/doi/10.1145/3613904.3642914][almost certainly student data]], becoming more and more reliant on enormous tech companies in ways that are honestly divergent from the goals of education. I suppose it's too much to ask at this current moment when every educational institution is scrambling to make deals with artificial AI companies that are, themselves, experiencing huge economic disruption and a growing sense that [[https://www.wsj.com/tech/ai/ai-bubble-building-spree-55ee6128][the bubble will soon burst]] but... I wish we could take the long-term view that [[/posts/2024-09-25-cannon-shot-epistemology/][digital technologies change over time]], often for the worse, into account. If not, we risk enshittifying education itself.
